import type { Metadata } from "next";
import "./index.scss";
export const metadata: Metadata = {
    title: "Create Turborepo",
    description: "Generated by create turbo",
};

export default function HomePageLayout({
    children,
}: {
    children: React.ReactNode;
}): JSX.Element {
    return (
        <main>
            <div className="admin-app">
                <section className="admin-app__side-bar">Side bar</section>
                <section className="admin-app__container">
                    <nav className="navbar">navbar</nav>
                    <article className="content">{children}</article>
                </section>
            </div>
        </main>
    );
}
